version: 0.2
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "github-to-lambda-demo"
        Alias: "github-to-lambda-a"
        CurrentVersion: "$LATEST"
        TargetVersion: "$LATEST"
Hooks:
  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeTrafficShift"
  - AfterAllowTraffic: "LambdaFunctionToValidateAfterTrafficShift"
