version: 0.2
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "github-to-lambda-demo"
        Alias: "github-to-lambda-a"
        CurrentVersion: "$LATEST"
        TargetVersion: "$LATEST"
Hooks:
  - BeforeInstall:
      - location: scripts/before-install.sh
        timeout: 300
        runas: root
      - location: lambda_function.py
  - AfterInstall:
      - location: scripts/after-install.sh
        timeout: 300
        runas: root
